Repository CS2113-AY1819S2-M11-2/main, pull requests merged in 2019-04, with the labels that each got.

#118 Added DeleteNotes Feature and updated ppp partially
  docs/team/justin-ong.adoc
  docs/team/khairulhazril.adoc
  docs/team/nicholasleeeee.adoc
  docs/team/shengkok.adoc
  notes.json
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNotesCommand.java
  src/main/java/seedu/address/logic/parser/AddNotesCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteNotesCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/NotesEvent.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/notes/Notes.java
  src/main/java/seedu/address/storage/JsonNotesStorage.java
  src/main/java/seedu/address/storage/NotesStorage.java
  src/main/java/seedu/address/ui/NotesCard.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Enhancement, type.Story, v1.4

#119 Update Docs
  .gitignore
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CalendarDemo.png
  docs/images/Ui.png
  docs/team/justin-ong.adoc
  notes.json
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/NotesCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task, v1.4

#122 Update PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/nicholasleeeee.adoc
Labels: priority.Medium, type.Task, v1.4

#125 Updated User and Developer Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AddNotesAfter.png
  docs/images/AddNotesBefore.png
  docs/images/DeleteNoteAfter.png
  docs/images/DeleteNoteBefore.png
Labels: type.Task, v1.4

#152 Calendar tweaks
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/ui/CalendarCell.java
  src/main/java/seedu/address/ui/CalendarCellTask.java
Labels: severity.Medium, type.Bug, type.Enhancement, v1.4

#157 Update PPP
  docs/team/justin-ong.adoc
Labels: type.Task, v1.4

#158 Update code contribution link
  docs/team/justin-ong.adoc
Labels: type.Task, v1.4

#160 Add Signup test case and update UG
  .gitignore
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/nicholasleeeee.adoc
  login.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/model/account/Password.java
  src/main/java/seedu/address/model/account/User.java
  src/main/java/seedu/address/model/account/Username.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
  src/test/java/seedu/address/logic/parser/SignupCommandParserTest.java
  src/test/java/seedu/address/testutil/AccountBuilder.java
  src/test/java/seedu/address/testutil/TypicalAccounts.java
Labels: severity.Low, type.Task, v1.4

#161 Update Calendar
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MonthCommand.java
  src/main/java/seedu/address/logic/parser/MonthCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/Month.java
  src/main/java/seedu/address/ui/CalendarCellTask.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
Labels: priority.High, status.Ongoing, type.Enhancement, v1.4

#163 Admin Updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CalendarBuildSequenceDiagram.png
  docs/images/CalendarClassDiagram.png
  docs/images/CalendarDemo.png
  docs/images/MonthCommandSequenceDiagram.png
  docs/images/Ui.png
  docs/team/justin-ong.adoc
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High, type.Task, v1.4

#162 Created test for notes
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
  src/test/java/seedu/address/model/notes/ContentTest.java
  src/test/java/seedu/address/model/notes/HeadingTest.java
  src/test/java/seedu/address/model/notes/NotesTest.java
  src/test/java/seedu/address/testutil/NotesBuilder.java
  src/test/java/seedu/address/testutil/TypicalNotes.java
Labels: priority.High, type.Task, v1.4

#164 Update Month Command
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/MonthCommand.java
  src/test/java/seedu/address/logic/commands/MonthCommandTest.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
  src/test/java/seedu/address/model/calendar/MonthTest.java
Labels: priority.High, type.Task, v1.4

#154 Update UG to fix errors
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/task/Due.java
Labels: type.Task, v1.4

#166 Reset Selected Task on Modifying Task List
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CalendarClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAccountCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/IncorrectCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/MonthCommand.java
  src/main/java/seedu/address/ui/CalendarCell.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Enhancement, v1.4

#167 Admin Tasks
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CalendarClassDiagram.png
  docs/images/StudentBuddy.png
  docs/images/TaskManager.png
  docs/team/justin-ong.adoc
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, type.Enhancement, type.Task, v1.4

#170 Add test case and update UGDG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/nicholasleeeee.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteAccountCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNotesCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindDateCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPriorityCommand.java
  src/main/java/seedu/address/logic/commands/FindUpcomingCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/MonthCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/GenerateHash.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteAccountCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindDateCommandTest.java
  src/test/java/seedu/address/logic/commands/FindModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPriorityCommandTest.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/MonthCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
  src/test/java/seedu/address/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SignupCommandParserTest.java
  src/test/java/seedu/address/model/account/PasswordTest.java
  src/test/java/seedu/address/model/account/UserTest.java
  src/test/java/seedu/address/model/account/UsernameTest.java
  src/test/java/seedu/address/testutil/AccountBuilder.java
Labels: priority.Medium, type.Task, v1.4

#171 Update PPP
  docs/UserGuide.adoc
  docs/team/khairulhazril.adoc
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindUpcomingCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindNameCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Task, v1.4

#169 Update UG, DG, PPP
  docs/DeveloperGuide.adoc
  docs/team/justin-ong.adoc
Labels: priority.High, type.Task, v1.4

#173 Edit status of tasks due today
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/task/Due.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/FindDateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPriorityCommandParserTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
Labels: priority.Medium, type.Task, v1.4

#174 Edit sample data
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#175 Update SampleDataUtil to fix crash on initial startup
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: severity.High, type.Bug, v1.4

#177 Update Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/TaskClassDiagram.png
  docs/team/khairulhazril.adoc
Labels: type.Task, v1.4

#178 Fix test cases and update UGDG
  .gitignore
  _reposense/config.json
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/nicholasleeeee.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAccountCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNotesCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindDateCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPriorityCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/MonthCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/GenerateHash.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/SignupCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/LoginEvent.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/account/Password.java
  src/main/java/seedu/address/model/account/User.java
  src/main/java/seedu/address/model/account/Username.java
  src/main/java/seedu/address/storage/JsonLoginStorage.java
  src/main/java/seedu/address/storage/LoginStorage.java
  src/test/java/seedu/address/logic/commands/AddNotesCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAccountCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
  src/test/java/seedu/address/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SignupCommandParserTest.java
  src/test/java/seedu/address/model/account/PasswordTest.java
  src/test/java/seedu/address/model/account/UserTest.java
  src/test/java/seedu/address/model/account/UsernameTest.java
  src/test/java/seedu/address/testutil/AccountBuilder.java
  src/test/java/seedu/address/testutil/TypicalAccounts.java
Labels: priority.Medium, type.Task, v1.4

#176 Bug fixes
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/data/JsonSerializableTaskManagerTest/duplicateTaskTaskManager.json
  src/test/java/seedu/address/logic/commands/AddNotesCommandTest.java
  src/test/java/seedu/address/model/TaskManagerTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
Labels: priority.High, type.Bug, v1.4

#179 Update PPP
  docs/DeveloperGuide.adoc
  docs/team/khairulhazril.adoc
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium, type.Task

#182 Update user stories
  docs/DeveloperGuide.adoc
Labels: type.Task, v1.4

#180 Update PPP
  docs/team/justin-ong.adoc
Labels: priority.High, type.Task, v1.4

#184 Update PPP
  docs/team/justin-ong.adoc
Labels: priority.High, type.Task, v1.4

#183 Fix test case and update PPP
  docs/team/nicholasleeeee.adoc
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddNotesCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAccountCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindDateCommandTest.java
  src/test/java/seedu/address/logic/commands/FindModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPriorityCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: priority.Medium, type.Task, v1.4

#186 Add Alias for sort parameters and update UG
  docs/UserGuide.adoc
  docs/team/khairulhazril.adoc
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
Labels: priority.Medium, type.Task, v1.4

#188 Fix typo
  docs/UserGuide.adoc
  docs/team/khairulhazril.adoc
Labels: type.Task, v1.4

#189 Fixed spelling errors in PPP
  docs/team/shengkok.adoc
Labels: priority.Low

#190 Final touches
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/nicholasleeeee.adoc
  src/test/java/seedu/address/logic/commands/DeleteAccountCommandTest.java
Labels: priority.Medium, type.Task, v1.4

#191 Edit DG
  docs/DeveloperGuide.adoc
  docs/team/khairulhazril.adoc
Labels: type.Task, v1.4

#192 Reformat DG
  docs/DeveloperGuide.adoc
Labels: type.Task, v1.4

#194 Add use case
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium, type.Task, v1.4

#195 Update UI pic
  docs/images/Ui.png
Labels: priority.High, type.Task, v1.4

#197 Fix admin permissions
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNotesCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindDateCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPriorityCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/MonthCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
Labels: priority.High, severity.High, type.Bug, v1.4

#196 Fix bug
  docs/UserGuide.adoc
Labels: help wanted, priority.High, type.Task, v1.4
