Repository CS2113-AY1819S2-M11-2/main, pull requests merged in 2019-03, with the labels that each got.

#5 v1.1 - Replace BrowserPanel with CalendarPanel
  docs/AboutUs.adoc
  docs/images/justin-ong.png
  docs/images/shengkok.png
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: High, v1.1

#15 justin[ong] with lowercase 'o'
  docs/AboutUs.adoc
Labels: duplicate

#16 Final change to photos. Checked all lowercases
  docs/images/justin-ong.png
Labels: bug, duplicate

#23 Added portfolio for the team
  docs/AboutUs.adoc
  docs/team/justin-ong.adoc
  docs/team/khairulhazril.adoc
  docs/team/nicholasleeeee.adoc
  docs/team/shengkok.adoc
Labels: priority.Low, v1.2

#31 Updated User Guide
  docs/UserGuide.adoc
Labels: priority.Medium

#32 Display Tasks on Calendar
  src/main/java/seedu/address/ui/CalendarCell.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarCell.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, status.Ongoing, type.Enhancement, v1.2

#37 Added Notes Feature
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/parser/AddNotesCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/notes/Content.java
  src/main/java/seedu/address/model/notes/Heading.java
  src/main/java/seedu/address/model/notes/Notes.java
  src/main/java/seedu/address/model/notes/UniqueNotesList.java
  src/main/java/seedu/address/model/notes/exceptions/DuplicateNotesException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: v1.2

#39 V1.2 Add Sort Function
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskManager.java
  src/main/java/seedu/address/model/task/SortTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#51 Add sort feature to User Guide
  docs/UserGuide.adoc
Labels: priority.Medium

#54 Update Developer Guide
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/TaskManager.java
Labels: type.Task

#36 Update Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/CalendarBuildSequenceDiagram.png
  docs/images/Ui.png
  src/main/java/seedu/address/ui/CalendarCell.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
Labels: priority.High, type.Task, v1.2

#63 Added Signup, Login, Logout feature and updated UDGD
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/logic/commands/IncorrectCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/logic/parser/GenerateHash.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/SignupCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/LoginEvent.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/login/Password.java
  src/main/java/seedu/address/model/login/User.java
  src/main/java/seedu/address/model/login/Username.java
  src/main/java/seedu/address/storage/JsonLoginStorage.java
  src/main/java/seedu/address/storage/LoginStorage.java
Labels: priority.Medium, v1.3

#64 Enable Dynamic Updating of Calendar
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, type.Enhancement, v1.3

#65 Add FindModule, FindName, FindPriority features
  login.json
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPriorityCommand.java
  src/main/java/seedu/address/logic/parser/FindModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/FindNameCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPriorityCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/task/ModuleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/PriorityContainsKeywordsPredicate.java
Labels: priority.Medium

#72 Calendar Enhancements
  README.adoc
  docs/UserGuide.adoc
  docs/images/CalendarDemo.png
  docs/images/Ui.png
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/address/ui/CalendarCell.java
  src/main/java/seedu/address/ui/CalendarCellTask.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarPanel.fxml
Labels: priority.Medium, status.Ongoing, type.Enhancement, v1.3

#78 Update User Guide
  docs/UserGuide.adoc
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Low, type.Task, v1.3

#80 Add sort by date feature
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Due.java
  src/main/java/seedu/address/model/task/SortTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/CalendarCell.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/DateTest.java
  src/test/java/seedu/address/model/task/DueTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/TaskManagerSystemTest.java
Labels: priority.Medium, type.Enhancement

#84 Admin Updates
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/LearningOutcomes.adoc
  docs/UserGuide.adoc
  docs/templates/_header.html.slim
Labels: priority.High, type.Task, v1.3

#83 Login feature enhancement
  docs/UserGuide.adoc
  login.json
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GenerateHash.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SignupCommandParser.java
  src/main/java/seedu/address/model/LoginEvent.java
  src/main/java/seedu/address/model/login/Password.java
  src/main/java/seedu/address/model/login/User.java
  src/main/java/seedu/address/model/login/Username.java
  src/main/java/seedu/address/storage/JsonLoginStorage.java
Labels: priority.Medium, type.Enhancement, v1.3

#86 Update website
  build.gradle
  docs/ContactUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CalendarDemo.png
  docs/images/Ui.png
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
Labels: priority.Medium, status.Ongoing, type.Task, v1.3

#90 Update Docs
  .gitignore
  README.adoc
  docs/DeveloperGuide.adoc
  login.json
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/CalendarCell.java
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonTaskManagerStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.High, status.Ongoing, type.Task, v1.3

#94 Add daysLeft to Task Card
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/TaskCardHandle.java
  src/test/java/guitests/guihandles/TaskListPanelHandle.java
  src/test/java/seedu/address/storage/JsonTaskManagerStorageTest.java
  src/test/java/seedu/address/ui/TaskCardTest.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/TaskManagerSystemTest.java
Labels: priority.Medium, type.Enhancement, v1.3

#100 Add admin feature
  src/main/java/seedu/address/logic/commands/DeleteAccountCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/LoginEvent.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonLoginStorage.java
Labels: priority.Medium, type.Enhancement, v1.3

#101 Insert login check for important commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: priority.Medium, type.Task, v1.3

#102 Fix deleteacc bug
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/model/LoginEvent.java
Labels: priority.High, severity.High, type.Bug, v1.3

#103 Fix admin bug and update developer guide
  docs/DeveloperGuide.adoc
  docs/images/DeleteAccountSequenceDiagram.png
  docs/images/LoginSequenceDiagram.png
  docs/images/LogoutSequenceDiagram.png
  docs/images/SignUpSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAccountCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/LoginEvent.java
Labels: priority.High, severity.High, type.Bug, v1.3

#104 Fix login bug
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddNotesCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/storage/JsonLoginStorage.java
  src/main/java/seedu/address/storage/LoginStorage.java
Labels: priority.High, severity.High, type.Bug, v1.3

#106 Updated developer guide section 2 and notes feature
  docs/DeveloperGuide.adoc
  docs/images/AddNotesSequenceDiagram.png
Labels: type.Task

#107 Updated developer guide
  docs/DeveloperGuide.adoc
  docs/images/AccountClassDiagram.png
  docs/images/DeleteAccountSequenceDiagram.png
  docs/images/LoginSequenceDiagram.png
  docs/images/LogoutSequenceDiagram.png
  docs/images/SignUpSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteAccountCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SignupCommandParser.java
  src/main/java/seedu/address/model/LoginEvent.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/account/Password.java
  src/main/java/seedu/address/model/account/User.java
  src/main/java/seedu/address/model/account/Username.java
  src/main/java/seedu/address/storage/JsonLoginStorage.java
  src/main/java/seedu/address/storage/LoginStorage.java
Labels: priority.Medium, type.Task, v1.3

#108 Update Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/CalendarBuildSequenceDiagram.png
  docs/images/CalendarClassDiagram.png
  src/main/java/seedu/address/ui/CalendarCellTask.java
Labels: priority.High, type.Task, v1.3

#109 Update DG
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task, v1.3

#110 Update Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/DeletePersonSdForLogic.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassBetterOopDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SDforDeletePerson.png
  docs/images/SortSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  login.json
  src/main/java/seedu/address/logic/commands/FindUpcomingCommand.java
  src/main/java/seedu/address/logic/parser/FindDateCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskManagerParser.java
  src/main/java/seedu/address/model/task/Due.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FindDateCommandTest.java
  src/test/java/seedu/address/logic/commands/FindModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPriorityCommandTest.java
  src/test/java/seedu/address/logic/parser/TaskManagerParserTest.java
  src/test/java/seedu/address/model/TaskManagerTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/TaskManagerSystemTest.java
Labels: priority.Medium, type.Task, v1.3

#111 Update calendar tests
  .gitignore
  docs/images/CalendarClassDiagram.png
  src/main/java/seedu/address/ui/CalendarPanel.java
  src/test/java/guitests/guihandles/CalendarPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/TaskListPanelHandle.java
  src/test/java/seedu/address/ui/CalendarPanelTest.java
  src/test/java/seedu/address/ui/TaskListPanelTest.java
Labels: priority.High, type.Task, v1.3

#112 Fix login bug
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/logic/parser/SignupCommandParser.java
Labels: priority.High, severity.High, v1.3

#114 Update Tests
  docs/DeveloperGuide.adoc
  src/test/java/seedu/address/ui/CalendarPanelTest.java
Labels: priority.High, type.Task, v1.3
